verbatim:
  cabal-version: 3.4

name: cooked-validators
version: 0.2.0
extra-source-files:
  - README.md

dependencies:
  - QuickCheck
  - array
  - base
  - cardano-ledger-core
  - mtl
  - optics-core
  - plutus-tx
  - plutus-ledger-api
  - strict-containers
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - flat
  - bytestring
  - plutus-core

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wno-missed-extra-shared-lib
    -fobject-code
    -fno-ignore-interface-pragmas
    -fno-omit-interface-pragmas
    -fplugin-opt PlutusTx.Plugin:defer-errors

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/
    dependencies:
      - cooked-validators
